project_name: got
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - mac
    goarch:
      - amd64
      - arm64
dockers:
- image_templates: ["ghcr.io/macanton/got:{{ .Version }}"]
  dockerfile: Dockerfile
  build_flag_templates:
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/macanton/got
  - --label=org.opencontainers.image.source=https://github.com/macanton/got
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT
