env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  -
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: arm64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
brews:
  -
    name: got
    tap:
      owner: macanton
      name: homebrew-got
    description: CLI tool for manipulating git branches together with Jira tickets
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
